### DISCUSSION TITLE
Support getting requirements from local source

### DISCUSSION THREAD

**Discussion by notatallshaw** [pradyunsg/pip-resolver-benchmarks#17] [Functionality]
I want to be able to create a local pyproject.toml that looks like this:

```toml
[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta"

[project]
name = "reproducer"
authors = [
    {name = "reproducer"}
]
version = "0.0.1"
description = "reproducer"
dependencies = [
    "adlfs~=2023.1",
    "dask[complete]~=2021.10",
    "gcsfs>=2023.1, <2023.3",
]
```

And I want to fetch the requirements from this. 

The reason is, resolvelib behaves different to whether somehting is a direct requirement or a transative requirement, and I want to create a scenario where   "adlfs~=2023.1", "dask[complete]~=2021.10", and "gcsfs>=2023.1, <2023.3", are all transitive requirements.
